---

- name: Test if NagiosCore is installed
  systemd:
    state: started
    name: nagios
  register: result

- name: copy nagios.cfg template
  template:
    src: template_nagios.cfg.j2
    dest: "{{ nagios_install_path }}etc/nagios.cfg"
    owner: nagios
    group: nagios
    force: yes
    backup: yes

- name: create the directory where the hosts config file will be stored
  file:
    path: "{{ nagios_install_path }}Servers/"
    state: directory

- name: copy host.cfg template
  template:
    src: host.cfg.j2
    dest: "{{ nagios_install_path }}Servers/{{ item }}.cfg"
    owner: nagios
    group: nagios
    mode: '664'
  with_inventory_hostnames:
    - all:!Nagios_Core

- name: copy hostgroup.cfg template
  template:
    src: hostgroups.cfg.j2
    dest: "{{ nagios_install_path }}etc/objects/hostgroups.cfg"
    owner: nagios
    group: nagios
    mode: '664'

- name: copy templates.cfg
  template:
    src: templates.cfg.j2
    dest: "{{ nagios_install_path }}etc/objects/templates.cfg"
    owner: nagios
    group: nagios
    mode: '664'

- name: restart nagios service
  systemd:
    state: restarted
    name: nagios
